## @file
# File templates/pr-gate-build-job.yml
#
# template file used to build supported packages.
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2020 - 2021, ARM Limited. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

parameters:
  tool_chain_tag: ''
  vm_image: ''
  arch_list: ''

# Build step
jobs:

- job: Build_${{ parameters.tool_chain_tag }}

  #Use matrix to speed up the build process
  strategy:
    matrix:
      TARGET_OTHER:
        Build.Pkgs: 'ShellPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET'
      TARGET_FMP_FAT:
        Build.Pkgs: 'FmpDevicePkg,FatPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
      TARGET_CRYPTO:
        Build.Pkgs: 'CryptoPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET'

  workspace:
    clean: all

  pool:
    vmImage: ${{ parameters.vm_image }}

  steps:
  - template: pr-gate-steps.yml
    parameters:
      tool_chain_tag: ${{ parameters.tool_chain_tag }}
      build_pkgs: $(Build.Pkgs)
      build_targets: $(Build.Targets)
      build_archs: ${{ parameters.arch_list }}

- job: FINISHED
  dependsOn: Build_${{ parameters.tool_chain_tag }}
  condition: succeeded()
  steps:
  - checkout: none
  - script: |
      echo FINISHED
      sleep 10
    displayName: FINISHED

- job: FAILED
  dependsOn: Build_${{ parameters.tool_chain_tag }}
  condition: failed()
  steps:
  - checkout: none
  - script: |
      echo FAILED
      sleep 10
    displayName: FAILED
