## @file
# codecov upload configuration file to carryforward coverage results of
# packages that do not upload coverage results for a given pull request.
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
flags:
  EmbeddedPkg:
    carryforward: true
  FatPkg:
    carryforward: true
  FmpDevicePkg:
    carryforward: true
  PrmPkg:
    carryforward: true
  SecurityPkg:
    carryforward: true
  SourceLevelDebugPkg:
    carryforward: true
