/** @file
  Defines last attempt status codes used in the FmpDevicePkg.

  Copyright (c) Microsoft Corporation.<BR>

  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

// MU_CHANGE Starts

#ifndef __FMP_LAST_ATTEMPT_STATUS_H__
#define __FMP_LAST_ATTEMPT_STATUS_H__

//
// Size of the error code range for FMP driver-specific errors
//
#define LAST_ATTEMPT_STATUS_DRIVER_ERROR_COUNT              0x80

//
// Size of the error code range for FMP dependency related errors
//
#define LAST_ATTEMPT_STATUS_DEPENDENCY_ERROR_COUNT          0x20

#define LAST_ATTEMPT_STATUS_DRIVER_MAX_ERROR_CODE_VALUE     LAST_ATTEMPT_STATUS_ERROR_UNSUCCESSFUL_VENDOR_RANGE_MIN + \
                                                            LAST_ATTEMPT_STATUS_DRIVER_ERROR_COUNT

#define LAST_ATTEMPT_STATUS_DEPENDENCY_MAX_ERROR_CODE_VALUE LAST_ATTEMPT_STATUS_DRIVER_MAX_ERROR_CODE_VALUE + \
                                                            LAST_ATTEMPT_STATUS_DEPENDENCY_ERROR_COUNT

#define LAST_ATTEMPT_STATUS_LIBRARY_MAX_ERROR_CODE_VALUE    LAST_ATTEMPT_STATUS_ERROR_UNSUCCESSFUL_VENDOR_RANGE_MAX

//
// Last attempt status codes defined for additional granularity in the FMP driver stack.
//
// These codes are defined within the higher-level UEFI specification defined UNSUCCESSFUL_VENDOR_RANGE.
//
// The following last attempt status code ranges are defined for the following corresponding component:
//   * LAST_ATTEMPT_STATUS_DRIVER - FMP driver
//   * LAST_ATTEMPT_STATUS_DEPENDENCY - FMP dependency functionality
//   * LAST_ATTEMPT_STATUS_LIBRARY - FMP device library instances
//
enum LAST_ATTEMPT_STATUS_EXPANDED_ERROR_LIST
{
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_GETFMPHEADER             = LAST_ATTEMPT_STATUS_ERROR_UNSUCCESSFUL_VENDOR_RANGE_MIN,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_IMAGE_INVALID            ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_PROGRESS_CALLBACK_ERROR  ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_CHECKPWR_API             ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_CHECKSYSTHERMAL_API      ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_THERMAL                  ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_CHECKSYSENV_API          ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_SYSTEM_ENV               ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_GETFMPHEADERSIZE         ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_GETALLHEADERSIZE         ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_GETFMPHEADER_VERSION     ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_IMAGE_NOT_PROVIDED       ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_IMAGE_NOT_UPDATABLE      ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_INVALID_CERTIFICATE      ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_INVALID_IMAGE_INDEX      ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_INVALID_KEY_LENGTH       ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_INVALID_KEY_LENGTH_VALUE ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_VERSION_TOO_LOW          ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_DEVICE_LOCKED            ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_IMAGE_AUTH_FAILURE       ,
  LAST_ATTEMPT_STATUS_DRIVER_ERROR_MAX_ERROR_CODE           = LAST_ATTEMPT_STATUS_DRIVER_MAX_ERROR_CODE_VALUE,

  LAST_ATTEMPT_STATUS_DEPENDENCY_ERROR_GET_DEPEX_FAILURE,
  LAST_ATTEMPT_STATUS_DEPENDENCY_ERROR_NO_END_OPCODE,
  LAST_ATTEMPT_STATUS_DEPENDENCY_ERROR_UNKNOWN_OPCODE,
  LAST_ATTEMPT_STATUS_DEPENDENCY_ERROR_MEMORY_ALLOCATION_FAILED,
  LAST_ATTEMPT_STATUS_DEPENDENCY_ERROR_GUID_BEYOND_DEPEX,
  LAST_ATTEMPT_STATUS_DEPENDENCY_ERROR_VERSION_BEYOND_DEPEX,
  LAST_ATTEMPT_STATUS_DEPENDENCY_ERROR_VERSION_STR_BEYOND_DEPEX,
  LAST_ATTEMPT_STATUS_DEPENDENCY_ERROR_FMP_NOT_FOUND,
  LAST_ATTEMPT_STATUS_DEPENDENCY_ERROR_PUSH_FAILURE,
  LAST_ATTEMPT_STATUS_DEPENDENCY_ERROR_POP_FAILURE,
  LAST_ATTEMPT_STATUS_DEPENDENCY_ERROR_MAX_ERROR_CODE       = LAST_ATTEMPT_STATUS_DEPENDENCY_MAX_ERROR_CODE_VALUE,

  LAST_ATTEMPT_STATUS_LIBRARY_ERROR_MIN_ERROR_CODE,
  LAST_ATTEMPT_STATUS_LIBRARY_ERROR_MAX_ERROR_CODE          = LAST_ATTEMPT_STATUS_LIBRARY_MAX_ERROR_CODE_VALUE
};

#endif

// MU_CHANGE Ends
