## @file
# Azure Pipeline build file for a build using Windows and the Visual Studio compiler
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
# MU_CHANGE [BEGIN]
trigger:
- dev/*
- release/202208
- release/202202

schedules:
- cron: "0 8 * * 0,3"   # Sun/Wed at 1AM Pacific
  displayName: Sun/Wed Build
  branches:
    include:
    - dev/*
    - release/202208
    - release/202202
  always: true          # Always build, even if no changes

pr:
- dev/*
- release/202208
- release/202202

resources:
  repositories:
  - repository: basecore
    type: github
    name: Microsoft/mu_basecore
    ref: refs/heads/release/202208
    endpoint: Microsoft
# MU_CHANGE [END]

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'VS2022'
    vm_image: 'windows-2022'
    arch_list: "IA32,X64"
